# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Template_AH.ui'
#
# Created: Sun Jun 11 19:52:09 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1310, 740)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        self.Frame_Perspective = QtGui.QLabel(Form)
        self.Frame_Perspective.setGeometry(QtCore.QRect(10, 10, 300, 600))
        self.Frame_Perspective.setAutoFillBackground(False)
        self.Frame_Perspective.setFrameShape(QtGui.QFrame.Box)
        self.Frame_Perspective.setLineWidth(1)
        self.Frame_Perspective.setMidLineWidth(15)
        self.Frame_Perspective.setText(_fromUtf8(""))
        self.Frame_Perspective.setObjectName(_fromUtf8("Frame_Perspective"))
        self.Frame_puck = QtGui.QLabel(Form)
        self.Frame_puck.setGeometry(QtCore.QRect(315, 10, 300, 600))
        self.Frame_puck.setAutoFillBackground(False)
        self.Frame_puck.setFrameShape(QtGui.QFrame.Box)
        self.Frame_puck.setLineWidth(1)
        self.Frame_puck.setMidLineWidth(15)
        self.Frame_puck.setText(_fromUtf8(""))
        self.Frame_puck.setObjectName(_fromUtf8("Frame_puck"))
        self.Frame_prediction = QtGui.QLabel(Form)
        self.Frame_prediction.setGeometry(QtCore.QRect(620, 10, 300, 600))
        self.Frame_prediction.setAutoFillBackground(False)
        self.Frame_prediction.setFrameShape(QtGui.QFrame.Box)
        self.Frame_prediction.setLineWidth(1)
        self.Frame_prediction.setMidLineWidth(15)
        self.Frame_prediction.setText(_fromUtf8(""))
        self.Frame_prediction.setObjectName(_fromUtf8("Frame_prediction"))
        self.Frame_4 = QtGui.QLabel(Form)
        self.Frame_4.setGeometry(QtCore.QRect(925, 10, 300, 600))
        self.Frame_4.setAutoFillBackground(False)
        self.Frame_4.setFrameShape(QtGui.QFrame.Box)
        self.Frame_4.setLineWidth(1)
        self.Frame_4.setMidLineWidth(15)
        self.Frame_4.setText(_fromUtf8(""))
        self.Frame_4.setObjectName(_fromUtf8("Frame_4"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 700, 131, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.Left_bottom = QtGui.QGridLayout(self.layoutWidget)
        self.Left_bottom.setMargin(0)
        self.Left_bottom.setObjectName(_fromUtf8("Left_bottom"))
        self.X_lb = QtGui.QSpinBox(self.layoutWidget)
        self.X_lb.setMinimum(440)
        self.X_lb.setMaximum(640)
        self.X_lb.setProperty("value", 634)
        self.X_lb.setObjectName(_fromUtf8("X_lb"))
        self.Left_bottom.addWidget(self.X_lb, 0, 0, 1, 1)
        self.Y_lb = QtGui.QSpinBox(self.layoutWidget)
        self.Y_lb.setMaximum(200)
        self.Y_lb.setProperty("value", 91)
        self.Y_lb.setObjectName(_fromUtf8("Y_lb"))
        self.Left_bottom.addWidget(self.Y_lb, 0, 1, 1, 1)
        self.layoutWidget_2 = QtGui.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(180, 640, 128, 29))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.Right_top = QtGui.QGridLayout(self.layoutWidget_2)
        self.Right_top.setMargin(0)
        self.Right_top.setObjectName(_fromUtf8("Right_top"))
        self.Y_rt = QtGui.QSpinBox(self.layoutWidget_2)
        self.Y_rt.setMinimum(280)
        self.Y_rt.setMaximum(480)
        self.Y_rt.setProperty("value", 384)
        self.Y_rt.setObjectName(_fromUtf8("Y_rt"))
        self.Right_top.addWidget(self.Y_rt, 0, 1, 1, 1)
        self.X_rt = QtGui.QSpinBox(self.layoutWidget_2)
        self.X_rt.setMaximum(200)
        self.X_rt.setProperty("value", 9)
        self.X_rt.setObjectName(_fromUtf8("X_rt"))
        self.Right_top.addWidget(self.X_rt, 0, 0, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(180, 700, 131, 29))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.Right_bottom = QtGui.QGridLayout(self.layoutWidget_3)
        self.Right_bottom.setMargin(0)
        self.Right_bottom.setObjectName(_fromUtf8("Right_bottom"))
        self.Y_rb = QtGui.QSpinBox(self.layoutWidget_3)
        self.Y_rb.setMinimum(280)
        self.Y_rb.setMaximum(480)
        self.Y_rb.setProperty("value", 406)
        self.Y_rb.setObjectName(_fromUtf8("Y_rb"))
        self.Right_bottom.addWidget(self.Y_rb, 0, 1, 1, 1)
        self.X_rb = QtGui.QSpinBox(self.layoutWidget_3)
        self.X_rb.setMinimum(440)
        self.X_rb.setMaximum(640)
        self.X_rb.setProperty("value", 624)
        self.X_rb.setObjectName(_fromUtf8("X_rb"))
        self.Right_bottom.addWidget(self.X_rb, 0, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 620, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 620, 66, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 680, 91, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 680, 91, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 640, 128, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.Left_top = QtGui.QGridLayout(self.layoutWidget1)
        self.Left_top.setMargin(0)
        self.Left_top.setObjectName(_fromUtf8("Left_top"))
        self.X_lt = QtGui.QSpinBox(self.layoutWidget1)
        self.X_lt.setMaximum(200)
        self.X_lt.setProperty("value", 27)
        self.X_lt.setObjectName(_fromUtf8("X_lt"))
        self.Left_top.addWidget(self.X_lt, 0, 0, 1, 1)
        self.Y_lt = QtGui.QSpinBox(self.layoutWidget1)
        self.Y_lt.setMaximum(200)
        self.Y_lt.setProperty("value", 75)
        self.Y_lt.setObjectName(_fromUtf8("Y_lt"))
        self.Left_top.addWidget(self.Y_lt, 0, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(370, 700, 194, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.High = QtGui.QGridLayout(self.layoutWidget_4)
        self.High.setMargin(0)
        self.High.setObjectName(_fromUtf8("High"))
        self.Hue_h = QtGui.QSpinBox(self.layoutWidget_4)
        self.Hue_h.setMaximum(180)
        self.Hue_h.setProperty("value", 73)
        self.Hue_h.setObjectName(_fromUtf8("Hue_h"))
        self.High.addWidget(self.Hue_h, 0, 0, 1, 1)
        self.Sat_H = QtGui.QSpinBox(self.layoutWidget_4)
        self.Sat_H.setMaximum(255)
        self.Sat_H.setProperty("value", 157)
        self.Sat_H.setObjectName(_fromUtf8("Sat_H"))
        self.High.addWidget(self.Sat_H, 0, 1, 1, 1)
        self.Val_H = QtGui.QSpinBox(self.layoutWidget_4)
        self.Val_H.setMaximum(255)
        self.Val_H.setProperty("value", 255)
        self.Val_H.setObjectName(_fromUtf8("Val_H"))
        self.High.addWidget(self.Val_H, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(435, 620, 81, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(430, 680, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(370, 640, 194, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.Low = QtGui.QGridLayout(self.layoutWidget2)
        self.Low.setMargin(0)
        self.Low.setObjectName(_fromUtf8("Low"))
        self.Hue_L = QtGui.QSpinBox(self.layoutWidget2)
        self.Hue_L.setMaximum(180)
        self.Hue_L.setProperty("value", 34)
        self.Hue_L.setObjectName(_fromUtf8("Hue_L"))
        self.Low.addWidget(self.Hue_L, 0, 0, 1, 1)
        self.Sat_L = QtGui.QSpinBox(self.layoutWidget2)
        self.Sat_L.setMaximum(255)
        self.Sat_L.setProperty("value", 47)
        self.Sat_L.setObjectName(_fromUtf8("Sat_L"))
        self.Low.addWidget(self.Sat_L, 0, 1, 1, 1)
        self.Val_L = QtGui.QSpinBox(self.layoutWidget2)
        self.Val_L.setMaximum(255)
        self.Val_L.setProperty("value", 80)
        self.Val_L.setObjectName(_fromUtf8("Val_L"))
        self.Low.addWidget(self.Val_L, 0, 2, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(590, 650, 81, 61))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.Dilate = QtGui.QGridLayout(self.layoutWidget3)
        self.Dilate.setMargin(0)
        self.Dilate.setObjectName(_fromUtf8("Dilate"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Dilate.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.Dilate.addWidget(self.spinBox, 1, 0, 1, 1)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(690, 640, 211, 81))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.X_cms = QtGui.QLCDNumber(self.widget)
        self.X_cms.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.X_cms.setFont(font)
        self.X_cms.setAutoFillBackground(False)
        self.X_cms.setFrameShadow(QtGui.QFrame.Plain)
        self.X_cms.setMode(QtGui.QLCDNumber.Dec)
        self.X_cms.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.X_cms.setProperty("intValue", 90)
        self.X_cms.setObjectName(_fromUtf8("X_cms"))
        self.gridLayout.addWidget(self.X_cms, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.Y_cms = QtGui.QLCDNumber(self.widget)
        self.Y_cms.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Y_cms.setFont(font)
        self.Y_cms.setAutoFillBackground(False)
        self.Y_cms.setFrameShadow(QtGui.QFrame.Plain)
        self.Y_cms.setMode(QtGui.QLCDNumber.Dec)
        self.Y_cms.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Y_cms.setProperty("intValue", 50)
        self.Y_cms.setObjectName(_fromUtf8("Y_cms"))
        self.gridLayout.addWidget(self.Y_cms, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Right Top", None))
        self.label_2.setText(_translate("Form", "Left Top", None))
        self.label_3.setText(_translate("Form", "Left Bottom", None))
        self.label_4.setText(_translate("Form", "Right Bottom", None))
        self.label_5.setText(_translate("Form", "Low Range", None))
        self.label_6.setText(_translate("Form", "High Range", None))
        self.label_7.setText(_translate("Form", "Iterations", None))
        self.label_8.setText(_translate("Form", "<>", None))
        self.label_10.setText(_translate("Form", "cms", None))
        self.label_9.setText(_translate("Form", "Depth", None))
        self.label_11.setText(_translate("Form", "cms", None))

